// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otqlqcbbfhfadfuauptn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90cWxxY2JiZmhmYWRmdWF1cHRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzQ0OTksImV4cCI6MjA2NzQxMDQ5OX0.5EXC59W1Yw6NS0f_dPjK2aQOftZ99R_y-Trt7SubJKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});